# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendars', '0002_fitfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitfile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitfile',
            name='uploaded_file',
            field=models.FileField(upload_to=b'fit_file_uploads/%Y/%m/%d/%M/%S'),
        ),
    ]
