# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_auto_20190421_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitfile',
            name='title',
        ),
    ]
